# fly.toml app configuration file generated for backend-hidden-butterfly-2266 on 2025-11-07T11:56:59+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-hidden-butterfly-2266"
primary_region = "arn"

[build]
  dockerfile = "./Dockerfile"

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    soft_limit = 20
    hard_limit = 30

  [[http_service.checks]]
    interval = "30s"
    timeout = "5s"
    grace_period = "20s"
    method = "GET"
    path = "/health"

[[vm]]
  size = "shared-cpu-1x"
