app = "backend-hidden-butterfly-2266"
primary_region = "arn"

[build]
dockerfile = "./Dockerfile"

[deploy]
strategy = "rolling"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3_001
min_machines_running = 0
processes = [ "app" ]

  [[http_service.checks]]
  grace_period = "20s"
  interval = "30s"
  method = "GET"
  path = "/health"
  timeout = "5s"

  [http_service.concurrency]
  hard_limit = 30
  soft_limit = 20
  type = "requests"

[[vm]]
size = "shared-cpu-1x"